export const ICON_OPTIONS = [
  { label: "Private Pool", iconName: "Waves" },
  { label: "Gym", iconName: "Dumbbell" },
  { label: "Security", iconName: "ShieldCheck" },
  { label: "Pets Allowed", iconName: "PawPrint" },
  { label: "Parking", iconName: "Car" },
  { label: "Jacuzzi", iconName: "Bath" },
  { label: "Balcony", iconName: "DoorOpen" },
  { label: "WiFi", iconName: "Wifi" },
  { label: "Air Conditioning", iconName: "Snowflake" },
  { label: "Barbecue", iconName: "Flame" },
  { label: "TV", iconName: "Tv" },
  { label: "Laundry", iconName: "WashingMachine" },
  { label: "Kitchen", iconName: "Utensils" },
  { label: "Spa", iconName: "Sparkles" },
  { label: "Game Room", iconName: "Gamepad2" },
  { label: "Fireplace", iconName: "Fireplace" },
  { label: "Mountain View", iconName: "Mountain" },
  { label: "Beach Access", iconName: "Umbrella" },
  { label: "Lift / Elevator", iconName: "MoveUp" },
  { label: "CCTV Surveillance", iconName: "Camera" },
  { label: "24/7 Power Backup", iconName: "BatteryCharging" },
  { label: "Clubhouse", iconName: "Building" },
  { label: "Playground", iconName: "Slides" },
  { label: "Garden", iconName: "Trees" },
  { label: "Reception / Lobby", iconName: "Bell" },
  { label: "Conference Room", iconName: "Presentation" },
  { label: "Housekeeping", iconName: "Broom" },
  { label: "Rooftop Access", iconName: "Landmark" },
  { label: "Wheelchair Accessible", iconName: "Accessibility" },
  { label: "Smoke Detector", iconName: "AlarmSmoke" },
  { label: "First Aid", iconName: "HeartPulse" },
  { label: "Library", iconName: "BookOpenCheck" },
  { label: "Bicycle Parking", iconName: "Bike" },
  { label: "ATM Nearby", iconName: "CreditCard" },

  // More Amenities
  { label: "Shuttle Service", iconName: "Bus" },
  { label: "Pet Area", iconName: "Dog" },
  { label: "Open Air Theatre", iconName: "Theater" },
  { label: "Laundry Room", iconName: "Shirt" },
  { label: "Daycare", iconName: "Baby" },
  { label: "Grocery Store", iconName: "ShoppingCart" },
  { label: "Pharmacy", iconName: "Capsule" },
  { label: "Café", iconName: "Coffee" },
  { label: "Restaurant", iconName: "ChefHat" },
  { label: "Music Room", iconName: "Music2" },
  { label: "Prayer Room", iconName: "Church" },
  { label: "Bonfire Area", iconName: "Campfire" },
  { label: "Skate Park", iconName: "Skateboard" },
  { label: "Ping Pong", iconName: "Table2" },
  { label: "Basketball Court", iconName: "Dribbble" },
  { label: "Tennis Court", iconName: "Racket" },
  { label: "Cricket Net", iconName: "Cricket" },
  { label: "Badminton Court", iconName: "Feather" },
  { label: "EV Charging", iconName: "ChargingStation" },
  { label: "Co-working Space", iconName: "Laptop2" },
  { label: "Workspace", iconName: "Briefcase" },
  { label: "Lounge Area", iconName: "Sofa" },
  { label: "Reception Desk", iconName: "UserRoundCheck" },
  { label: "Meditation Room", iconName: "Lotus" },
  { label: "Cinema Room", iconName: "Clapperboard" },
  { label: "Art Gallery", iconName: "Palette" },
  { label: "Scenic View", iconName: "Binoculars" },
  { label: "Walking Trail", iconName: "Footprints" },
  { label: "Yoga Deck", iconName: "StretchHorizontal" },
  { label: "Cold Storage", iconName: "ThermometerSnowflake" },
  { label: "Pantry", iconName: "Sandwich" },
  { label: "Parcel Locker", iconName: "PackageCheck" },
  { label: "Rainwater Harvesting", iconName: "Droplets" },
  { label: "Solar Power", iconName: "Sun" },
  { label: "Visitor Parking", iconName: "ParkingCircle" },
  { label: "Mosque", iconName: "MoonStar" },
  { label: "Temple", iconName: "Landmark" },
];
